#!/bin/bash
menu(){
clear
echo productos
echo 1 cargar productos
echo 2 calcular iva
echo 3 salir
read op
case $op in

1)cargar;;
2)calc;;
3)salir;;
esac
}

cargar(){
clear
echo ingrese un producto
read prod
total=$((prod+total))
echo desea ingresar otro producto 1=si 2=no
read opc
case $opc in
1)cargar;;
2)menu;;
esac
}
calc(){
clear
echo precio total
echo el precio total es $total
sleep 3
menu
}
menu
