#!/bin/bash

menu(){
echo operaciones con variables
echo 1-suma
echo 2-salir

read op

case $op in

1)suma;;
2)salir;;

esac
}
suma(){
clear
echo ingrese dos numeros
echo ingrese numero 1
read num1
echo ingrese numero 2
read num2

suma=$((num1+num2))
suma2=$((suma*22/100))
echo el resultado de la suma es $suma2
sleep 2
menu
}
salir(){
clear
echo saliendo
sleep 2
exit
}
menu
