#!/bin/bash


menu(){

echo 1= SUMA
echo 2= RESTA
echo 3= MULTIPLICACIÓN 
echo 4= DIVISIÓN

read op
case $op in

1)suma;;
2)resta;;
3)multi;;
4)divi;;
*)echo "opcion incorrecta";;
esac
}

divi(){
cer=0
echo realizar div
read -p "ingrese primer numero= " num1 
read -p "ingrese segundo numero= " num2 
if [$num2 -eq [0]]; then
echo "no se puede dividir entre 000"
sleep 3
fi
div=$((num1/num2))
echo "division" $div
sleep 3
menu
}
menu
