#!/bin/bash

echo "Seleccione una operacion:"
echo "1. Sumar"
echo "2. Restar"
echo "3. Multiplicar"
echo "4. Dividir"
read opcion

echo "Ingrese el primer numero:"
read num1
echo "Ingrese el segundo numero:"
read num2

case $opcion in
1) echo "Resultado: $(($num1 + $num2))";;
2) echo "Resultado: $(($num1 - $num2))";;
3) echo "Resultado: $((num1 * $num2))";;
4) echo "Resultado: $(echo "scale=2; $num1 / $num2")";;
*) echo "Opcion invalida";;
esac
