#!/bin/bash

while true; do
 echo "Seleccione una opcion:"
 echo "1. Uso de disco"
 echo "2. Uso de memoria"
 echo "3. Procesos activos"
 echo "4. Salir"
 read opcion

case $opcion in
 1) df -h;;
 2) free -m;;
 3) ps aux;;
 4) exit;;
 *) echo "Opcion invalida";;
esac
done
